// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-equipment.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/data.ts
var EQUIPMENT = [
  { id: "TR-01", type: "Power Transformer", status: "Operational", health: 98.2, params: { voltage: "1000 kV", current: "3200 A", oilTemp: "62\xB0C", load: "72%", cooling: "ONAN Active", dga: "Normal" } },
  { id: "TR-02", type: "Power Transformer", status: "Operational", health: 97.8, params: { voltage: "1000 kV", current: "2850 A", oilTemp: "58\xB0C", load: "65%", cooling: "ONAN Active", dga: "Normal" } },
  { id: "TR-03", type: "Power Transformer", status: "Maintenance", health: 89.1, params: { voltage: "995 kV", current: "1200 A", oilTemp: "45\xB0C", load: "28%", cooling: "Reduced", dga: "Watch" } },
  { id: "CB-01", type: "Circuit Breaker", status: "Closed", health: 96, params: { rated: "1000 kV", breaking: "63 kA", operations: "1247", lastTrip: "None" } },
  { id: "CB-02", type: "Circuit Breaker", status: "Closed", health: 95.4, params: { rated: "1000 kV", breaking: "63 kA", operations: "892", lastTrip: "12 days ago" } },
  { id: "CB-03", type: "Circuit Breaker", status: "Open", health: 82.5, params: { rated: "1000 kV", breaking: "63 kA", operations: "2103", lastTrip: "2 hrs ago" } },
  { id: "SA-01", type: "Surge Arrester", status: "Active", health: 99, params: { rating: "1000 kV", leakage: "0.2 mA", discharges: "3" } },
  { id: "SA-02", type: "Surge Arrester", status: "Active", health: 99.3, params: { rating: "1000 kV", leakage: "0.15 mA", discharges: "1" } },
  { id: "CAP-01", type: "Capacitor Bank", status: "Online", health: 94.7, params: { capacity: "200 MVAr", voltage: "1000 kV", temperature: "35\xB0C", steps: "3/4" } }
];
var GRID_STATUS = {
  substation: "Substation Alpha",
  gridVoltageKv: 1e3,
  frequencyHz: 50,
  currentLoadMw: 3200,
  peakLoadMw: 3450,
  transmissionEfficiencyPct: 98.2,
  activeSensors: 247,
  offlineSensors: 3,
  equipmentFaults: 1,
  totalUnits: 24
};
var CARBON_METRICS = {
  carbonRateTonnesPerHour: 12.4,
  renewableSharePct: 35,
  carbonScore: 72,
  reductionVsBaselinePct: 18.5,
  offsetsVerifiedOnLedger: true
};
var ALERTS = [
  { id: "ALM-1041", severity: "warning", source: "CB-03", message: "Breaker opened after fault current detection", time: "2 hrs ago" },
  { id: "ALM-1039", severity: "warning", source: "Grid Sync", message: "Synchronisation latency above 80 ms", time: "3 hrs ago" },
  { id: "ALM-1032", severity: "info", source: "TR-03", message: "Scheduled maintenance window active", time: "9 hrs ago" }
];

// src/lib/mcp/tools/list-equipment.ts
var list_equipment_default = defineTool({
  name: "list_equipment",
  title: "List substation equipment",
  description: "List all monitored UHV substation equipment (transformers, circuit breakers, surge arresters, capacitor banks) with status and health score.",
  inputSchema: {
    type: z.string().optional().describe("Optional filter on equipment type, e.g. 'Power Transformer' or 'Circuit Breaker'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ type }) => {
    const items = type ? EQUIPMENT.filter((e) => e.type.toLowerCase().includes(type.toLowerCase())) : EQUIPMENT;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/get-equipment.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_equipment_default = defineTool2({
  name: "get_equipment",
  title: "Get equipment details",
  description: "Get the full digital-twin parameter set for one piece of equipment by its ID (e.g. TR-01, CB-03, CAP-01).",
  inputSchema: { id: z2.string().trim().min(1).describe("Equipment ID such as TR-01.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const item = EQUIPMENT.find((e) => e.id.toLowerCase() === id.toLowerCase());
    if (!item) throw new ToolError(`No equipment found with ID "${id}".`);
    return {
      content: [{ type: "text", text: JSON.stringify(item, null, 2) }],
      structuredContent: { item }
    };
  }
});

// src/lib/mcp/tools/get-grid-status.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_grid_status_default = defineTool3({
  name: "get_grid_status",
  title: "Get grid status",
  description: "Get the live command-overview grid status: voltage, frequency, load, transmission efficiency, sensor counts and equipment faults.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(GRID_STATUS, null, 2) }],
    structuredContent: GRID_STATUS
  })
});

// src/lib/mcp/tools/get-carbon-metrics.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_carbon_metrics_default = defineTool4({
  name: "get_carbon_metrics",
  title: "Get carbon metrics",
  description: "Get carbon-neutrality metrics for the substation: real-time CO2 output rate, renewable share, carbon score and reduction versus baseline.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CARBON_METRICS, null, 2) }],
    structuredContent: CARBON_METRICS
  })
});

// src/lib/mcp/tools/list-alerts.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_alerts_default = defineTool5({
  name: "list_alerts",
  title: "List active alerts",
  description: "List the active monitoring alerts for the substation, optionally filtered by severity.",
  inputSchema: {
    severity: z3.enum(["critical", "warning", "info"]).optional().describe("Optional severity filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ severity }) => {
    const items = severity ? ALERTS.filter((a) => a.severity === severity) : ALERTS;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "onoanwlgafltmgvdembr";
var mcp_default = defineMcp({
  name: "smart-carbon-grid",
  title: "Smart Carbon Grid",
  version: "0.1.0",
  instructions: "Tools for the Smart Carbon Neutral UHV monitoring system. Use `get_grid_status` for the live substation overview, `list_equipment` / `get_equipment` for digital-twin equipment telemetry, `list_alerts` for active alerts, and `get_carbon_metrics` for carbon-neutrality figures.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_grid_status_default, list_equipment_default, get_equipment_default, list_alerts_default, get_carbon_metrics_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
